name: run-black

on:
    push:
        branches: "*"
    pull_request:
        branches: master

jobs:
    black:
        name: black
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v1
            - name: set up python
              uses: actions/actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: install black
              run: python -m pip install black
            - name: run black
              run: black --check notebooks/utils/

