name: Continuous Integration
on:
    push:
        branches:
            -   "*"
    pull_request:
        branches:
            -   "*"

jobs:
    build:
        name: Test on ubuntu
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            -   name: Install conda
                uses: goanpeca/setup-miniconda@v1
                with:
                    auto-update-conda: true

            -   name: Set up environment
                shell: bash -l {0}
                run: |
                    echo $PWD
                    ls
                    ls environments/ || echo "ls failed"
                    conda env create -f environments/environment.yaml || echo "conda env create failed"
                    conda activate hires-marbl || echo "conda activate failed"

            -   name: Show conda environment
                shell: bash -l {0}
                run: conda list

            -   name: Run Tests
                shell: bash -l {0}
                run: pytest -v tests/
