name: Continuous Integration
on:
    push:
        branches:
            -   "*"
    pull_request:
        branches:
            -   "*"

jobs:
    build:
        name: Test on ubuntu
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            -   uses: goanpeca/setup-miniconda@v1
                with:
                    activate-environment: hires-marbl
                    auto-update-conda: true
                    environment-file: environments/environment.yml
            -   name: Show conda environment
                shell: bash -l {0}
                run: conda list

            -   name: Run Tests
                shell: bash -l {0}
                run: pytest tests/
